
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kiwine
 */
public class AdminEmployee extends javax.swing.JFrame {

   private String StoreID="CH85650";
   
    public AdminEmployee() {
        initComponents();
        UIManager.getDefaults().put("Button.disabledShadow", Color.RED);
        this.setLocationRelativeTo(null);
        table();
        LoadCbYear();
        LoadCbMonth();
        LoadCbStaff();
        //this.StoreID = txtStoreID.getText();
        this.StoreID = "CH85650";
        txtStoreID.setText(this.StoreID);
    }
    
    //custom table
    public void table(){
        TableStatistic.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,14));
        TableStatistic.getTableHeader().setBackground(new Color(99, 100, 171));
        TableStatistic.getTableHeader().setOpaque(false);
        TableStatistic.getTableHeader().setForeground(new Color(229, 218, 233));
        TableStatistic.setRowHeight(30);
        
        tableSalary.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,14));
        tableSalary.getTableHeader().setBackground(new Color(99, 100, 171));
        tableSalary.getTableHeader().setOpaque(false);
        tableSalary.getTableHeader().setForeground(new Color(229, 218, 233));
        tableSalary.setRowHeight(30);
        
        //
        //panelDetail.setVisible(false);
        panelQuota.setVisible(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TbPanelEmployee = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtStoreID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStatistic = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        cbYear = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnStatistic = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUpdateStatistic = new javax.swing.JButton();
        btnAddStatistic = new javax.swing.JButton();
        panelQuota = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbMonthAdd = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbYearAdd1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        txtSetNewQuota = new javax.swing.JTextField();
        btnSaveQuota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        SCbMonth = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SCbStaffID = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        SCbYear = new javax.swing.JComboBox<>();
        SbtnStatistic = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSalary = new javax.swing.JTable();
        SbtnAdd = new javax.swing.JButton();
        SbtnUpdate = new javax.swing.JButton();
        SbtnSave = new javax.swing.JButton();
        txtDayOff = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        txtStaffID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        StxtMonth = new javax.swing.JTextField();
        StxtYear = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(31, 34, 46));

        TbPanelEmployee.setBackground(new java.awt.Color(31, 34, 46));
        TbPanelEmployee.setForeground(new java.awt.Color(184, 185, 208));

        jPanel1.setBackground(new java.awt.Color(31, 34, 46));

        jPanel3.setBackground(new java.awt.Color(31, 34, 46));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home Page.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 221, 209));
        jLabel1.setText("QUẢN LÝ NHÂN SỰ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(31, 34, 46));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(224, 221, 209));
        jLabel2.setText("Cửa hàng số: ");

        txtStoreID.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtStoreID.setForeground(new java.awt.Color(146, 150, 208));
        txtStoreID.setText("1000");

        TableStatistic.setAutoCreateRowSorter(true);
        TableStatistic.setBackground(new java.awt.Color(31, 34, 46));
        TableStatistic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableStatistic.setForeground(new java.awt.Color(231, 220, 234));
        TableStatistic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tháng", "Năm", "Mã nhân viên", "Số đơn hàng", "Doanh số", "Quota Sale", "Hiệu suất"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableStatistic.setFocusable(false);
        TableStatistic.setGridColor(new java.awt.Color(31, 34, 46));
        TableStatistic.setRowHeight(40);
        TableStatistic.setSelectionBackground(new java.awt.Color(181, 185, 222));
        TableStatistic.setShowGrid(false);
        jScrollPane1.setViewportView(TableStatistic);
        if (TableStatistic.getColumnModel().getColumnCount() > 0) {
            TableStatistic.getColumnModel().getColumn(0).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(1).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(2).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(3).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(4).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(5).setPreferredWidth(10);
            TableStatistic.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbYear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 220, 234));
        jLabel5.setText("Tháng");

        cbMonth.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbMonth.setToolTipText("");
        cbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 220, 234));
        jLabel6.setText("Năm");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        btnStatistic.setBackground(new java.awt.Color(146, 150, 208));
        btnStatistic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStatistic.setForeground(new java.awt.Color(69, 73, 100));
        btnStatistic.setText("Thống kê");
        btnStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatisticMouseClicked(evt);
            }
        });
        btnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(136, 137, 191));
        jLabel4.setText("Nhân viên thu ngân");

        btnUpdateStatistic.setBackground(new java.awt.Color(146, 150, 208));
        btnUpdateStatistic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateStatistic.setForeground(new java.awt.Color(69, 73, 100));
        btnUpdateStatistic.setText("Cập nhật");
        btnUpdateStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateStatisticMouseClicked(evt);
            }
        });
        btnUpdateStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatisticActionPerformed(evt);
            }
        });

        btnAddStatistic.setBackground(new java.awt.Color(146, 150, 208));
        btnAddStatistic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStatistic.setForeground(new java.awt.Color(69, 73, 100));
        btnAddStatistic.setText("Thêm");
        btnAddStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStatisticMouseClicked(evt);
            }
        });
        btnAddStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStatisticActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("QUOTA SALE THÁNG MỚI");

        cbMonthAdd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbMonthAdd.setToolTipText("");
        cbMonthAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthAddActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(87, 81, 161));
        jLabel24.setText("Tháng");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(87, 81, 161));
        jLabel26.setText("Năm");

        cbYearAdd1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbYearAdd1.setToolTipText("");
        cbYearAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearAdd1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(87, 81, 161));
        jLabel27.setText("Đặt Quota Sale");

        txtSetNewQuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetNewQuotaActionPerformed(evt);
            }
        });

        btnSaveQuota.setBackground(new java.awt.Color(58, 54, 107));
        btnSaveQuota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaveQuota.setForeground(new java.awt.Color(213, 213, 227));
        btnSaveQuota.setText("Xác nhận");
        btnSaveQuota.setBorder(null);
        btnSaveQuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveQuotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuotaLayout = new javax.swing.GroupLayout(panelQuota);
        panelQuota.setLayout(panelQuotaLayout);
        panelQuotaLayout.setHorizontalGroup(
            panelQuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(74, 74, 74))
            .addGroup(panelQuotaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelQuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel24)
                    .addComponent(cbMonthAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbYearAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtSetNewQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelQuotaLayout.setVerticalGroup(
            panelQuotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuotaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel23)
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addGap(9, 9, 9)
                .addComponent(cbMonthAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbYearAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSetNewQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnSaveQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStoreID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(btnStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnUpdateStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAddStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelQuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtStoreID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        TbPanelEmployee.addTab("Giao diện chính", jPanel1);

        jPanel2.setBackground(new java.awt.Color(31, 34, 46));
        jPanel2.setForeground(new java.awt.Color(69, 73, 100));

        jPanel4.setBackground(new java.awt.Color(31, 34, 46));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SCbMonth.setBackground(new java.awt.Color(184, 185, 208));
        SCbMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SCbMonth.setForeground(new java.awt.Color(66, 66, 114));
        SCbMonth.setBorder(null);
        jPanel4.add(SCbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Tháng");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Mã nhân viên");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        SCbStaffID.setBackground(new java.awt.Color(184, 185, 208));
        SCbStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SCbStaffID.setForeground(new java.awt.Color(66, 66, 114));
        SCbStaffID.setBorder(null);
        jPanel4.add(SCbStaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Năm");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        SCbYear.setBackground(new java.awt.Color(184, 185, 208));
        SCbYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SCbYear.setForeground(new java.awt.Color(66, 66, 114));
        SCbYear.setBorder(null);
        jPanel4.add(SCbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, -1));

        SbtnStatistic.setBackground(new java.awt.Color(213, 213, 227));
        SbtnStatistic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SbtnStatistic.setForeground(new java.awt.Color(67, 67, 115));
        SbtnStatistic.setText("Thống kê");
        SbtnStatistic.setBorder(null);
        SbtnStatistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnStatisticActionPerformed(evt);
            }
        });
        jPanel4.add(SbtnStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 182, 34));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(31, 34, 46));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(231, 220, 234));
        jLabel12.setText("  Quản lý lương");
        jPanel6.add(jLabel12, java.awt.BorderLayout.CENTER);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Money Bag Bitcoin.png"))); // NOI18N
        jPanel6.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jSeparator2.setBackground(new java.awt.Color(69, 73, 100));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tableSalary.setAutoCreateRowSorter(true);
        tableSalary.setBackground(new java.awt.Color(31, 34, 46));
        tableSalary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableSalary.setForeground(new java.awt.Color(231, 220, 234));
        tableSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Năm", "Mã nhân viên", "Lương cố định", "Lương thưởng", "Số ngày nghỉ", "Tiền bị trừ", "Tổng lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSalary.setFocusable(false);
        tableSalary.setGridColor(new java.awt.Color(31, 34, 46));
        tableSalary.setOpaque(false);
        tableSalary.setRowHeight(40);
        tableSalary.setSelectionBackground(new java.awt.Color(181, 185, 222));
        tableSalary.setShowGrid(false);
        tableSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSalaryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSalary);
        if (tableSalary.getColumnModel().getColumnCount() > 0) {
            tableSalary.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(1).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(2).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(3).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(4).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(5).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(6).setPreferredWidth(10);
            tableSalary.getColumnModel().getColumn(7).setPreferredWidth(10);
        }

        SbtnAdd.setBackground(new java.awt.Color(213, 213, 227));
        SbtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SbtnAdd.setForeground(new java.awt.Color(69, 73, 100));
        SbtnAdd.setText("Thêm");
        SbtnAdd.setBorder(null);
        SbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnAddActionPerformed(evt);
            }
        });

        SbtnUpdate.setBackground(new java.awt.Color(213, 213, 227));
        SbtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SbtnUpdate.setForeground(new java.awt.Color(69, 73, 100));
        SbtnUpdate.setText("Cập nhật");
        SbtnUpdate.setBorder(null);
        SbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnUpdateActionPerformed(evt);
            }
        });

        SbtnSave.setBackground(new java.awt.Color(213, 213, 227));
        SbtnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SbtnSave.setForeground(new java.awt.Color(69, 73, 100));
        SbtnSave.setText("Lưu thay đổi");
        SbtnSave.setBorder(null);
        SbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnSaveActionPerformed(evt);
            }
        });

        txtDayOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDayOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayOffActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(213, 213, 227));
        jLabel20.setText("Số ngày nghỉ");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(213, 213, 227));
        jLabel19.setText("Lương cố định");

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        txtLastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastname.setForeground(new java.awt.Color(31, 34, 46));
        txtLastname.setEnabled(false);
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });

        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(31, 34, 46));
        txtFirstname.setEnabled(false);
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        txtStaffID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStaffID.setForeground(new java.awt.Color(31, 34, 46));
        txtStaffID.setEnabled(false);
        txtStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIDActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(213, 213, 227));
        jLabel16.setText("Mã nhân viên");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(213, 213, 227));
        jLabel17.setText("Họ");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(213, 213, 227));
        jLabel18.setText("Tên");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(213, 213, 227));
        jLabel21.setText("Tháng");

        StxtMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StxtMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StxtMonthActionPerformed(evt);
            }
        });

        StxtYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StxtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StxtYearActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(213, 213, 227));
        jLabel22.setText("Năm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDayOff, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StxtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SbtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(SbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(SbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDayOff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StxtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(StxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        TbPanelEmployee.addTab("Quản lý lương", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TbPanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TbPanelEmployee)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatisticActionPerformed

    
    private void btnStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticMouseClicked
        //thống kê theo tháng và năm
        String month = cbMonth.getSelectedItem().toString();
        String year = cbYear.getSelectedItem().toString();

        try{
            
            ResultSet rs = new DBUpdater().GetStatisticEmployeeByStore(
                                                StoreID, Integer.parseInt(month), Integer.parseInt(year));
           
            DefaultTableModel model=(DefaultTableModel)TableStatistic.getModel();
            int i=0;
            if (!rs.next()){
                JOptionPane.showMessageDialog(this,"Thống kê thất bại!");
            }else{
                while(rs.next()){
            
               String thang = rs.getString(1);
               String nam  = rs.getString(2);
               String manv = rs.getString(3);
               String sodonghang = rs.getString(4);
               String doanhso = rs.getString(5);
               String quota = rs.getString(6);
               String hieusuat = rs.getString(7);
               //JOptionPane.showMessageDialog(this, thang + " " + nam);
               Object[] row = {thang,nam,manv,sodonghang,doanhso,quota,hieusuat};
              // model.addRow(row);
               model.insertRow(i, row);
                }
              JOptionPane.showMessageDialog(this, "Thống kê thành công! ");
            
            }
           
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnStatisticMouseClicked

    private void LoadCbStaff(){
        try{
            ResultSet r = new DBUpdater().GetSaleStaffIDByStore(StoreID);
            while (r.next()){
                String manv = r.getString("MaNV");
                SCbStaffID.addItem(manv);
            } 
            
        }catch(Exception e){
            e.printStackTrace();
        }
       
    }
    private void cbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMonthActionPerformed

    private void SbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SbtnAddActionPerformed

    //button cap nhan luong
    private void SbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnUpdateActionPerformed
        SbtnUpdate.setVisible(false);
        SbtnSave.setVisible(true);
    }//GEN-LAST:event_SbtnUpdateActionPerformed

    private void SbtnStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnStatisticActionPerformed
        //thống kê theo tháng, năm thông tin của 1 nhân viên
        String month=SCbMonth.getSelectedItem().toString();
        String year = SCbYear.getSelectedItem().toString();
        String manv = SCbStaffID.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel)tableSalary.getModel();
        try{
            ResultSet rs = new DBUpdater().GetSalaryInfoByStaff(manv, Integer.parseInt(month),Integer.parseInt(year));
            while(rs.next()){
                String thang = rs.getString(1);
                String nam = rs.getString(2);
                String ma = rs.getString(3);
                String luongcd =rs.getString(4);
                String luongthuong = rs.getString(5);
                String songaynghi = rs.getString (6);
                String tienbitru = rs.getString(7);
                String tongluong = rs.getString(8);
                model.addRow(new Object[]{thang, nam, ma, luongcd, luongthuong,songaynghi,tienbitru,tongluong});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_SbtnStatisticActionPerformed
    
    private void LoadSalaryTable(String manv, int month, int year){
       
         DefaultTableModel model = (DefaultTableModel)tableSalary.getModel();
         //xóa all table row
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
        try{
             ResultSet rs = new DBUpdater().GetSalaryInfoByStaff(manv, month,year);
            while(rs.next()){
                String thang = rs.getString(1);
                String nam = rs.getString(2);
                String ma = rs.getString(3);
                String luongcd =rs.getString(4);
                String luongthuong = rs.getString(5);
                String songaynghi = rs.getString (6);
                String tienbitru = rs.getString(7);
                String tongluong = rs.getString(8);
                model.addRow(new Object[]{thang, nam, ma, luongcd, luongthuong,songaynghi,tienbitru,tongluong});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    private void txtStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIDActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void tableSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSalaryMouseClicked
        // TODO add your handling code here:
       // panelDetail.setVisible(true); //hien panel
        String id = tableSalary.getValueAt(tableSalary.getSelectedRow(), 2).toString();
        String luongcd = tableSalary.getValueAt(tableSalary.getSelectedRow(), 3).toString();
        String songaynghi = tableSalary.getValueAt(tableSalary.getSelectedRow(), 5).toString();
        String thang = tableSalary.getValueAt(tableSalary.getSelectedRow(), 0).toString();
        String nam = tableSalary.getValueAt(tableSalary.getSelectedRow(), 1).toString();
        
        txtDayOff.setText(songaynghi);
        txtSalary.setText(luongcd);
        txtStaffID.setText(id);
        StxtMonth.setText(thang);
        StxtYear.setText(nam);
        
        try{
            ResultSet rs = new DBUpdater().GetInfoStaff(id);
            rs.next();
            String honv = rs.getString(2);
            String ten = rs.getString(3);
            
            JOptionPane.showMessageDialog(this, ten);
            txtLastname.setText(honv);
            txtFirstname.setText(ten);
            
                    
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_tableSalaryMouseClicked

    private void txtDayOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayOffActionPerformed

    //lưu thay đổi cập nhật
    private void SbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnSaveActionPerformed
       SbtnUpdate.setVisible(true);
        String luongcd = txtSalary.getText();
       String songaynghi = txtDayOff.getText();
       String manv = txtStaffID.getText();
       int thang = Integer.parseInt(StxtMonth.getText());
       int nam = Integer.parseInt(StxtYear.getText());
       //cap nhat vao he thong
       int result=new DBUpdater().UpdateSalaryInfo(manv, Integer.parseInt(songaynghi), Integer.parseInt(luongcd), thang, nam);
       if (result > 0){
           JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
       }else{
           JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
       }
        LoadSalaryTable(manv, thang, nam);
    }//GEN-LAST:event_SbtnSaveActionPerformed

    private void StxtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StxtMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StxtMonthActionPerformed

    private void StxtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StxtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StxtYearActionPerformed

    private void btnUpdateStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStatisticMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStatisticMouseClicked

    private void btnUpdateStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStatisticActionPerformed

    private void btnAddStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStatisticMouseClicked
        //thêm quota sale cho tháng mới'
        btnAddStatistic.setVisible(false);
        panelQuota.setVisible(true);
    }//GEN-LAST:event_btnAddStatisticMouseClicked

    private void btnAddStatisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStatisticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStatisticActionPerformed

    private void cbMonthAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMonthAddActionPerformed

    private void cbYearAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearAdd1ActionPerformed

    private void txtSetNewQuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetNewQuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetNewQuotaActionPerformed

    private void btnSaveQuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveQuotaActionPerformed
        String mach = this.StoreID;
        int thang = Integer.parseInt(cbMonthAdd.getSelectedItem().toString());
        int nam = Integer.parseInt(cbYearAdd1.getSelectedItem().toString());
        String quota = txtSetNewQuota.getText();
        int quotasale=0;
        int result;
        if (quota.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập QuotaSale tháng mới!");
        }else{
            quotasale=Integer.parseInt(quota);
            try{
                result = new DBUpdater().AddNewQuotaSale(mach, thang, nam, quotasale);
                if (result>0){
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                           
                }
                else{
                    JOptionPane.showMessageDialog(this, "Thêm thất bại");
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
        btnAddStatistic.setVisible(true);
        panelQuota.setVisible(false);
        
    }//GEN-LAST:event_btnSaveQuotaActionPerformed

    private void LoadCbMonth(){
        cbMonth.removeAll();
        for (int i=1; i<=12; i++){
            cbMonth.addItem(Integer.toString(i));
            SCbMonth.addItem(Integer.toString(i));
            cbMonthAdd.addItem(Integer.toString(i));
        }
    }
    
    private void LoadCbYear(){
        cbYear.removeAll();
        for (int i=2030;i>=2000;i--){
            cbYear.addItem(Integer.toString(i));
            SCbYear.addItem(Integer.toString(i));
            cbYearAdd1.addItem(Integer.toString(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEmployee().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SCbMonth;
    private javax.swing.JComboBox<String> SCbStaffID;
    private javax.swing.JComboBox<String> SCbYear;
    private javax.swing.JButton SbtnAdd;
    private javax.swing.JButton SbtnSave;
    private javax.swing.JButton SbtnStatistic;
    private javax.swing.JButton SbtnUpdate;
    private javax.swing.JTextField StxtMonth;
    private javax.swing.JTextField StxtYear;
    private javax.swing.JTable TableStatistic;
    private javax.swing.JTabbedPane TbPanelEmployee;
    private javax.swing.JButton btnAddStatistic;
    private javax.swing.JButton btnSaveQuota;
    private javax.swing.JButton btnStatistic;
    private javax.swing.JButton btnUpdateStatistic;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbMonthAdd;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JComboBox<String> cbYearAdd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelQuota;
    private javax.swing.JTable tableSalary;
    private javax.swing.JTextField txtDayOff;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSetNewQuota;
    private javax.swing.JTextField txtStaffID;
    private javax.swing.JLabel txtStoreID;
    // End of variables declaration//GEN-END:variables
}
