
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 84978
 */
public class CustomerFrame extends javax.swing.JFrame {

    private static String customerId = "";
    private static String SuppliesId = "";
    private static String SuppliesName = "";
    private static String PercentDiscount = "";
    private static String SupplierID = "";
    private static long Cost = 0;
    private static int SuppliesRemainingQuantity =0;
    private static long TotalCost = 0;
    private static String StoreId = "";
    
    
    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame(String id) {
        customerId = new DBUpdater().getCustomerId(id);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        AddBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        SearchBox = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        FullNamelb = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        MaSPTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TenSPTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SoLuongTxt = new javax.swing.JTextField();
        SoLuongWarn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SoNhaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DuongTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhuongTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        QuanTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ThanhPhoTxt = new javax.swing.JTextField();
        ThanhToanCBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JButton();
        CacelBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SoNhaWarn = new javax.swing.JLabel();
        DuongWarn = new javax.swing.JLabel();
        PhuongWarn = new javax.swing.JLabel();
        QuanWarn = new javax.swing.JLabel();
        ThanhPhoWarn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TongTienTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PhiVanChuyenTxt = new javax.swing.JTextField();
        LogOut1 = new javax.swing.JLabel();
        FullNamelb1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FullNamelb2 = new javax.swing.JLabel();
        LogOut2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);

        jTabbedPane1.setBackground(java.awt.Color.white);

        jPanel1.setBackground(java.awt.Color.white);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá gốc", "Phầm trăm giảm giá", "Số lượng tồn", "Nhà cung cấp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        AddBtn.setText("Thêm vào giỏ hàng");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        jButton4.setText("Huỷ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        SearchBtn.setText("Tìm kiếm");
        SearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchBtnMouseClicked(evt);
            }
        });

        jLabel8.setText("Nhập mã/tên sản phẩm cần tìm kiếm");

        FullNamelb.setText(new DBUpdater().getCustomerFullName(customerId));

        LogOut.setForeground(java.awt.Color.red);
        LogOut.setText("Đăng xuất");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        MaSPTxt.setEditable(false);

        jLabel9.setText("Mã sản phẩm");

        jLabel11.setText("Tên sản phẩm");

        TenSPTxt.setEditable(false);

        jLabel12.setText("Số lượng");

        SoLuongTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoLuongTxtMouseClicked(evt);
            }
        });
        SoLuongTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoLuongTxtKeyTyped(evt);
            }
        });

        SoLuongWarn.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogOut)
                            .addComponent(FullNamelb, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(AddBtn)
                        .addGap(139, 139, 139)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(MaSPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(TenSPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SoLuongWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SoLuongTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(SearchBtn)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(FullNamelb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaSPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(TenSPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(SoLuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SoLuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn)
                    .addComponent(jButton4))
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Tìm kiếm", jPanel1);

        jPanel2.setBackground(java.awt.Color.white);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Phần trăm giá giảm", "Thành tiền", "Nhà cung cấp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Số nhà ");

        SoNhaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoNhaTxtKeyTyped(evt);
            }
        });

        jLabel2.setText("Đường");

        DuongTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DuongTxtKeyTyped(evt);
            }
        });

        jLabel3.setText("Phường");

        PhuongTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PhuongTxtKeyTyped(evt);
            }
        });

        jLabel4.setText("Quận");

        QuanTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuanTxtKeyTyped(evt);
            }
        });

        jLabel5.setText("Thành phố");

        ThanhPhoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ThanhPhoTxtKeyTyped(evt);
            }
        });

        ThanhToanCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thanh Toán Sau", "Thanh Toán Trước" }));

        jLabel6.setText("Hình thức thanh toán");

        ConfirmBtn.setText("Xác nhận");
        ConfirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmBtnMouseClicked(evt);
            }
        });

        CacelBtn.setText("Huỷ");
        CacelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CacelBtnMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ giao hàng:");

        jLabel10.setText("Giỏ hàng");

        SoNhaWarn.setForeground(java.awt.Color.red);

        DuongWarn.setForeground(java.awt.Color.red);

        PhuongWarn.setForeground(java.awt.Color.red);

        QuanWarn.setForeground(java.awt.Color.red);

        ThanhPhoWarn.setForeground(java.awt.Color.red);

        jLabel13.setText("Tổng tiền");

        TongTienTxt.setEditable(false);

        jLabel14.setText("Phí vận chuyển");

        PhiVanChuyenTxt.setEditable(false);

        LogOut1.setForeground(java.awt.Color.red);
        LogOut1.setText("Đăng xuất");
        LogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut1MouseClicked(evt);
            }
        });

        FullNamelb1.setText(new DBUpdater().getCustomerFullName(customerId));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(CacelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PhuongWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DuongTxt)
                                        .addComponent(PhuongTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addComponent(DuongWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(59, 59, 59)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SoNhaWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SoNhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PhiVanChuyenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ThanhPhoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                            .addComponent(ThanhPhoWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ThanhToanCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 104, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TongTienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(QuanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(QuanWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogOut1)
                            .addComponent(FullNamelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(FullNamelb1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(LogOut1))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TongTienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(PhiVanChuyenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SoNhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(QuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(QuanWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(ThanhPhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(PhuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(ThanhToanCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ConfirmBtn)
                                    .addComponent(CacelBtn)))
                            .addComponent(ThanhPhoWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SoNhaWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mua hàng", jPanel2);

        jPanel4.setBackground(java.awt.Color.white);

        jTable1.setModel(new DBUpdater().getOrderHistory(customerId)
        );
        jScrollPane1.setViewportView(jTable1);

        FullNamelb2.setText(new DBUpdater().getCustomerFullName(customerId));

        LogOut2.setForeground(java.awt.Color.red);
        LogOut2.setText("Đăng xuất");
        LogOut2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOut2)
                    .addComponent(FullNamelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(FullNamelb2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Lịch sử mua hàng", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchBtnMouseClicked
        String item = SearchBox.getText();
        DefaultTableModel dm  = new DBUpdater().SearchSupplies(item,StoreId);
        if(dm!=null){
            jTable3.setModel(dm);
        }
        else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm !!");
        }
        
        
    }//GEN-LAST:event_SearchBtnMouseClicked

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        Boolean check =true;
        long soLuong = 0;
        
        String SoLuong = SoLuongTxt.getText();
        if(SoLuong.equals("")){
            SoLuongWarn.setText("Nhập số lượng");
            check =false;
        }
        else{
             soLuong= Long.parseLong(SoLuong);
            if(soLuong <=0){
                SoLuongWarn.setText("Nhập số lượng lớn hơn 0");
                check =false;
            }
           
            if(soLuong>SuppliesRemainingQuantity ){
                SoLuongWarn.setText("Không thể cung cấp đủ");
                SoLuongTxt.setText(Integer.toString(SuppliesRemainingQuantity));
                check =false;
            }
        }
        
        
        if(check == true){
            String ThanhTien = Long.toString((100-Integer.parseInt(PercentDiscount))*(Cost)*soLuong/100);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            if(model.getRowCount()==0){
                model.addRow(new Object[]{SuppliesId,SuppliesName,SoLuong,PercentDiscount,ThanhTien,SupplierID});
                TotalCost+=Long.parseLong(ThanhTien);
                TongTienTxt.setText(Long.toString(TotalCost+30000)+" VNĐ");
                JOptionPane.showMessageDialog(this, "Thêm thành công !!");
                
                StoreId =new DBUpdater().getStoreId(SuppliesId);
                jTable3.setModel(new DBUpdater().SearchSupplies("", StoreId));
                PhiVanChuyenTxt.setText("30 000 VNĐ");
            }
            else{
                Boolean check_2 = true;
                int SoLuong_2 = 0;
                int currentStock = new DBUpdater().getInventoryQuantityofSupplies(SuppliesId);
                for (int row = 0 ; row < model.getRowCount(); row++){
                    if(SuppliesId.equals(jTable2.getValueAt(row,0))){
                        SoLuong_2+= Integer.parseInt((String)jTable2.getValueAt(row, 2));
                                            }
                }
                if(soLuong>(currentStock-SoLuong_2)){
                            SoLuongWarn.setText("Không thể cung cấp đủ");
                            SoLuongTxt.setText(Integer.toString(currentStock-SoLuong_2));
                            check_2 = false;
                        }
                if(check_2 == true){
                    model.addRow(new Object[]{SuppliesId,SuppliesName,SoLuong,PercentDiscount,ThanhTien,SupplierID});
        
                    jTable2.setModel(model);
                    JOptionPane.showMessageDialog(this, "Thêm thành công !!");
                    TotalCost+=Long.parseLong(ThanhTien);
                    TongTienTxt.setText(Long.toString(TotalCost+30000)+" VNĐ");
                    
                }
            }
            
        }
        
    }//GEN-LAST:event_AddBtnMouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        SuppliesId = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
        SuppliesName =jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
        SuppliesRemainingQuantity = Integer.parseInt(jTable3.getValueAt(jTable3.getSelectedRow(), 4).toString());
        PercentDiscount = jTable3.getValueAt(jTable3.getSelectedRow(), 3).toString();
        SupplierID =jTable3.getValueAt(jTable3.getSelectedRow(), 5).toString();
        Cost = Long.parseLong(jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString());
        MaSPTxt.setText(SuppliesId);
        TenSPTxt.setText(SuppliesName);
        
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void SoLuongTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoLuongTxtKeyTyped
        if(!(Character.isDigit(evt.getKeyChar()))){
                evt.consume();
            }
        
    }//GEN-LAST:event_SoLuongTxtKeyTyped

    private void SoLuongTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoLuongTxtMouseClicked
        SoLuongWarn.setText("");
    }//GEN-LAST:event_SoLuongTxtMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        int input = JOptionPane.showConfirmDialog(null, 
                "Đăng Xuất?", "Select an Option...",JOptionPane.YES_NO_OPTION);
        if(input == 0){
            setVisible(false);
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogOutMouseClicked

    private void ConfirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmBtnMouseClicked
        Boolean check = true;
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            if(model.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Giỏ hàng trống !!");
                check = false;
            }
        String Duong = DuongTxt.getText();
        
        if(Duong.equals("")){
            DuongWarn.setText("Nhập đường");
            check = false;
        }
        String SoNha = SoNhaTxt.getText();
        if(SoNha.equals("")){
            SoNhaWarn.setText("Nhập số nhà");
            check =false;
        }
        String Phuong = PhuongTxt.getText();
        if(Phuong.equals("")){
            PhuongWarn.setText("Nhập phường");
            check =false;
        }
        String Quan = QuanTxt.getText();
        if(Quan.equals("")){
            QuanWarn.setText("Nhập quận");
            check =false;
        }
        String ThanhPho = ThanhPhoTxt.getText();
        if(ThanhPho.equals("")){
            ThanhPhoWarn.setText("Nhập thành phố");
            check =false;
        }
        
        if(check == true){
            String MaDH = new Helper().generateUniqueOrderId();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now();
            String NgayDat = dtf.format(now);
            String HinhThucThanhToan = (String)ThanhToanCBox.getSelectedItem();
            String TrangThai = "Chờ giao";
            DBUpdater db = new DBUpdater();
            String MaNV = db.getSaleManId(StoreId);
            Boolean flag = true;
            if(db.insertNewOrder(MaDH, customerId, StoreId, NgayDat, SoNha, Duong, Phuong, Quan, ThanhPho, HinhThucThanhToan, TrangThai, MaNV)){
                
            }
            else flag = false;
            for(int i =0;i<model.getRowCount();i++){
                String MaSP = (String)model.getValueAt(i, 0);
                String SoLuongSanPham =(String)model.getValueAt(i, 2);
                if(!db.insertNewOrderDetail(MaDH,i+1, MaSP, SoLuongSanPham)){
                    flag = false;
                }
            }
            if(flag==true){
                jTable1.setModel(db.getOrderHistory(customerId));
                
                while(model.getRowCount()>0){
                    model.removeRow(0);
                }
                jTable3.setModel(db.SearchSupplies("", ""));
                TotalCost=0;
                StoreId ="";
                TongTienTxt.setText("");
                PhiVanChuyenTxt.setText("");
                JOptionPane.showMessageDialog(this, "Thành công !!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Lỗi !!");
            }
            
            
        }
    }//GEN-LAST:event_ConfirmBtnMouseClicked

    private void CacelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CacelBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        while(model.getRowCount()>0){
                    model.removeRow(0);
                }
        TotalCost=0;
        StoreId ="";
        TongTienTxt.setText("");
        PhiVanChuyenTxt.setText("");
        SoNhaTxt.setText("");
        DuongTxt.setText("");
        PhuongTxt.setText("");
        QuanTxt.setText("");
        ThanhPhoTxt.setText("");
    }//GEN-LAST:event_CacelBtnMouseClicked

    private void LogOut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut1MouseClicked
        int input = JOptionPane.showConfirmDialog(null, 
                "Đăng Xuất?", "Select an Option...",JOptionPane.YES_NO_OPTION);
        if(input == 0){
            setVisible(false);
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogOut1MouseClicked

    private void LogOut2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut2MouseClicked
        int input = JOptionPane.showConfirmDialog(null, 
                "Đăng Xuất?", "Select an Option...",JOptionPane.YES_NO_OPTION);
        if(input == 0){
            setVisible(false);
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_LogOut2MouseClicked

    private void SoNhaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SoNhaTxtKeyTyped
        int len = SoNhaTxt.getText().length();
        if(len == 5){
           evt.consume(); 
        }
    }//GEN-LAST:event_SoNhaTxtKeyTyped

    private void DuongTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DuongTxtKeyTyped
        int len = DuongTxt.getText().length();
        if(len == 30){
           evt.consume(); 
        }
    }//GEN-LAST:event_DuongTxtKeyTyped

    private void QuanTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuanTxtKeyTyped
        int len = QuanTxt.getText().length();
        if(len == 20){
           evt.consume(); 
        }
    }//GEN-LAST:event_QuanTxtKeyTyped

    private void PhuongTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhuongTxtKeyTyped
        int len = PhuongTxt.getText().length();
        if(len == 30){
           evt.consume(); 
        }
    }//GEN-LAST:event_PhuongTxtKeyTyped

    private void ThanhPhoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ThanhPhoTxtKeyTyped
        int len = ThanhPhoTxt.getText().length();
        if(len == 20){
           evt.consume(); 
        }
    }//GEN-LAST:event_ThanhPhoTxtKeyTyped

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        MaSPTxt.setText("");
        TenSPTxt.setText("");
        SoLuongTxt.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame(customerId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton CacelBtn;
    private javax.swing.JButton ConfirmBtn;
    private javax.swing.JTextField DuongTxt;
    private javax.swing.JLabel DuongWarn;
    private javax.swing.JLabel FullNamelb;
    private javax.swing.JLabel FullNamelb1;
    private javax.swing.JLabel FullNamelb2;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel LogOut1;
    private javax.swing.JLabel LogOut2;
    private javax.swing.JTextField MaSPTxt;
    private javax.swing.JTextField PhiVanChuyenTxt;
    private javax.swing.JTextField PhuongTxt;
    private javax.swing.JLabel PhuongWarn;
    private javax.swing.JTextField QuanTxt;
    private javax.swing.JLabel QuanWarn;
    private javax.swing.JTextField SearchBox;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SoLuongTxt;
    private javax.swing.JLabel SoLuongWarn;
    private javax.swing.JTextField SoNhaTxt;
    private javax.swing.JLabel SoNhaWarn;
    private javax.swing.JTextField TenSPTxt;
    private javax.swing.JTextField ThanhPhoTxt;
    private javax.swing.JLabel ThanhPhoWarn;
    private javax.swing.JComboBox<String> ThanhToanCBox;
    private javax.swing.JTextField TongTienTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
