
import javax.swing.JOptionPane;
import java.awt.Toolkit;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 84978
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TaiKhoanTxt = new javax.swing.JTextField();
        MatKhauTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        HoTxt = new javax.swing.JTextField();
        TenTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        SoNhaTxt = new javax.swing.JTextField();
        DuongTxt = new javax.swing.JTextField();
        PhuongTxt = new javax.swing.JTextField();
        QuanTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GioiTinhCBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ThanhPhoTxt = new javax.swing.JTextField();
        OkBtn = new javax.swing.JButton();
        CacelBtn = new javax.swing.JButton();
        NgaySinhTxt = new javax.swing.JFormattedTextField();
        SDTTxt = new javax.swing.JTextField();
        TKWarn = new javax.swing.JLabel();
        HoWarn = new javax.swing.JLabel();
        TenWarn = new javax.swing.JLabel();
        NgaySinhWarn = new javax.swing.JLabel();
        SDTWarn = new javax.swing.JLabel();
        EmailWarn = new javax.swing.JLabel();
        MKWarn = new javax.swing.JLabel();
        SoNhaWarn = new javax.swing.JLabel();
        DuongWarn = new javax.swing.JLabel();
        QuanWarn = new javax.swing.JLabel();
        PhuongWarn = new javax.swing.JLabel();
        ThanhPhoWarn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width  - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);
        setPreferredSize(new java.awt.Dimension(750, 630));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 608));

        jLabel1.setText("Tài khoản");

        TaiKhoanTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoanTxtMouseClicked(evt);
            }
        });
        TaiKhoanTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TaiKhoanTxtKeyTyped(evt);
            }
        });

        MatKhauTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatKhauTxtMouseClicked(evt);
            }
        });

        jLabel2.setText("Mật khẩu");

        HoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoTxtMouseClicked(evt);
            }
        });
        HoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HoTxtKeyTyped(evt);
            }
        });

        TenTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TenTxtMouseClicked(evt);
            }
        });
        TenTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TenTxtKeyTyped(evt);
            }
        });

        EmailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailTxtMouseClicked(evt);
            }
        });

        SoNhaTxt.setToolTipText("");
        SoNhaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoNhaTxtMouseClicked(evt);
            }
        });

        DuongTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DuongTxtMouseClicked(evt);
            }
        });

        PhuongTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhuongTxtMouseClicked(evt);
            }
        });

        QuanTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanTxtMouseClicked(evt);
            }
        });

        jLabel3.setText("Họ");

        jLabel4.setText("Tên");

        jLabel5.setText("Giới tính");

        GioiTinhCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel6.setText("Ngày sinh");

        jLabel7.setText("Số điện thoại");

        jLabel8.setText("Email");

        jLabel9.setText("Số nhà");

        jLabel10.setText("Đường");

        jLabel11.setText("Phường");

        jLabel12.setText("Quận");

        jLabel13.setText("Thành phố");

        ThanhPhoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThanhPhoTxtMouseClicked(evt);
            }
        });

        OkBtn.setText("OK");
        OkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkBtnMouseClicked(evt);
            }
        });
        OkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBtnActionPerformed(evt);
            }
        });

        CacelBtn.setText("Huỷ");
        CacelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CacelBtnMouseClicked(evt);
            }
        });

        NgaySinhTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NgaySinhTxtMouseClicked(evt);
            }
        });

        SDTTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SDTTxtMouseClicked(evt);
            }
        });
        SDTTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SDTTxtKeyTyped(evt);
            }
        });

        TKWarn.setForeground(java.awt.Color.red);

        HoWarn.setForeground(java.awt.Color.red);

        TenWarn.setForeground(java.awt.Color.red);

        NgaySinhWarn.setForeground(java.awt.Color.red);

        SDTWarn.setForeground(java.awt.Color.red);

        EmailWarn.setForeground(java.awt.Color.red);

        MKWarn.setForeground(java.awt.Color.red);

        SoNhaWarn.setForeground(java.awt.Color.red);

        DuongWarn.setForeground(java.awt.Color.red);

        QuanWarn.setForeground(java.awt.Color.red);

        PhuongWarn.setForeground(java.awt.Color.red);

        ThanhPhoWarn.setForeground(java.awt.Color.red);

        jLabel14.setText("Nhập theo format: YYYYmmDD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TaiKhoanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(HoTxt)
                            .addComponent(TKWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HoWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailWarn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TenTxt)
                            .addComponent(GioiTinhCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgaySinhTxt)
                            .addComponent(SDTTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(TenWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NgaySinhWarn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SDTWarn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MatKhauTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SoNhaWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(OkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addComponent(CacelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(QuanTxt)
                                    .addComponent(DuongTxt)
                                    .addComponent(SoNhaTxt)
                                    .addComponent(PhuongTxt)
                                    .addComponent(ThanhPhoTxt))
                                .addComponent(DuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(QuanWarn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ThanhPhoWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PhuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(MKWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TaiKhoanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatKhauTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TKWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MKWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(SoNhaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HoWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoNhaWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(DuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(GioiTinhCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(PhuongTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PhuongWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(QuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NgaySinhTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgaySinhWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuanWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(ThanhPhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SDTTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SDTWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThanhPhoWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkBtn)
                    .addComponent(CacelBtn)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(EmailWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkBtnActionPerformed

    private void HoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HoTxtKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isSpaceChar(evt.getKeyChar()))){
                evt.consume();
            }
        
        
    }//GEN-LAST:event_HoTxtKeyTyped

    private void TenTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TenTxtKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&&!(Character.isSpaceChar(evt.getKeyChar()))){
                evt.consume();
            }
    }//GEN-LAST:event_TenTxtKeyTyped

    private void SDTTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SDTTxtKeyTyped
        if(!(Character.isDigit(evt.getKeyChar()))){
                evt.consume();
            }
    }//GEN-LAST:event_SDTTxtKeyTyped

    private void CacelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CacelBtnMouseClicked
        setVisible(false);
    }//GEN-LAST:event_CacelBtnMouseClicked

    private void OkBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkBtnMouseClicked
        Boolean check = true;
        String MaKH = new Helper().generateUniqueCustomerId();
        String TaiKhoan =TaiKhoanTxt.getText();
        if(TaiKhoan.equals("")){
            TKWarn.setText("Nhập tài khoản");
            check =false;
        }
        else{
            if ((new DBUpdater().checkUniqueUserName(TaiKhoan))){
                TKWarn.setText("Tài khoản đã tồn tại");
                check = false;
            }
        }
        
       
        String MatKhau = MatKhauTxt.getText();
        if(MatKhau.equals("")){
            MKWarn.setText("Nhập mật khẩu");
            check =false;
        }
        String HoKH = HoTxt.getText();
        if(HoKH.equals("")){
            HoWarn.setText("Nhập họ");
            check =false;
        }
        String TenKH = TenTxt.getText();
        if(TenKH.equals("")){
            TenWarn.setText("Nhập tên");
            check =false;
        }
        String GioiTinh_KH = (String)GioiTinhCBox.getSelectedItem();
        if(GioiTinh_KH.equals("Nam")){
            GioiTinh_KH = "1";
        }
        else GioiTinh_KH = "0";
        
        String NgaySinh_KH = NgaySinhTxt.getText();
        if(NgaySinh_KH.equals("")){
            NgaySinhWarn.setText("Nhập ngày sinh");
            check =false;
        }
        String SDT_KH = SDTTxt.getText();
        if(SDT_KH.equals("")){
            SDTWarn.setText("Nhập số điện thoại");
            check =false;
        }
        String Email_KH = EmailTxt.getText();
        if(Email_KH.equals("")){
            EmailWarn.setText("Nhập email");
            check =false;
        }
         
        String Duong = DuongTxt.getText();
        if(Duong.equals("")){
            DuongWarn.setText("Nhập đường");
            check = false;
        }
        String SoNha = SoNhaTxt.getText();
        if(SoNha.equals("")){
            SoNhaWarn.setText("Nhập số nhà");
            check =false;
        }
        String Phuong = PhuongTxt.getText();
        if(Phuong.equals("")){
            PhuongWarn.setText("Nhập phường");
            check =false;
        }
        String Quan = QuanTxt.getText();
        if(Quan.equals("")){
            QuanWarn.setText("Nhập quận");
            check =false;
        }
        String ThanhPho = ThanhPhoTxt.getText();
        if(ThanhPho.equals("")){
            ThanhPhoWarn.setText("Nhập thành phố");
            check =false;
        }
        
        if(check == true){
            DBUpdater db = new DBUpdater();
            if(db.insertNewCustomerInformation(MaKH, HoKH, TenKH, GioiTinh_KH, NgaySinh_KH, SDT_KH, Email_KH, SoNha, Duong, Phuong, Quan, ThanhPho)&&db.insertNewCustomerAccount(MaKH, TaiKhoan, MatKhau)){
                JOptionPane.showMessageDialog(this, "Đăng ký thành công !!");
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Lỗi !!");
                
            }
        }
        
    }//GEN-LAST:event_OkBtnMouseClicked

    private void TaiKhoanTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanTxtMouseClicked
        TKWarn.setText("");
    }//GEN-LAST:event_TaiKhoanTxtMouseClicked

    private void MatKhauTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatKhauTxtMouseClicked
        MKWarn.setText("");
    }//GEN-LAST:event_MatKhauTxtMouseClicked

    private void HoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoTxtMouseClicked
        HoWarn.setText("");
    }//GEN-LAST:event_HoTxtMouseClicked

    private void TenTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TenTxtMouseClicked
        TenWarn.setText("");
    }//GEN-LAST:event_TenTxtMouseClicked

    private void SoNhaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoNhaTxtMouseClicked
        SoNhaWarn.setText("");
    }//GEN-LAST:event_SoNhaTxtMouseClicked

    private void DuongTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DuongTxtMouseClicked
        DuongWarn.setText("");
    }//GEN-LAST:event_DuongTxtMouseClicked

    private void PhuongTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhuongTxtMouseClicked
        PhuongWarn.setText("");
    }//GEN-LAST:event_PhuongTxtMouseClicked

    private void QuanTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanTxtMouseClicked
        QuanWarn.setText("");
    }//GEN-LAST:event_QuanTxtMouseClicked

    private void NgaySinhTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NgaySinhTxtMouseClicked
        NgaySinhWarn.setText("");
    }//GEN-LAST:event_NgaySinhTxtMouseClicked

    private void SDTTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SDTTxtMouseClicked
        SDTWarn.setText("");
    }//GEN-LAST:event_SDTTxtMouseClicked

    private void ThanhPhoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThanhPhoTxtMouseClicked
        ThanhPhoWarn.setText("");
    }//GEN-LAST:event_ThanhPhoTxtMouseClicked

    private void EmailTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTxtMouseClicked
        EmailWarn.setText("");
    }//GEN-LAST:event_EmailTxtMouseClicked

    private void TaiKhoanTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TaiKhoanTxtKeyTyped
        if(!(Character.isDigit(evt.getKeyChar()))){
                evt.consume();
            }
    }//GEN-LAST:event_TaiKhoanTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CacelBtn;
    private javax.swing.JTextField DuongTxt;
    private javax.swing.JLabel DuongWarn;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel EmailWarn;
    private javax.swing.JComboBox<String> GioiTinhCBox;
    private javax.swing.JTextField HoTxt;
    private javax.swing.JLabel HoWarn;
    private javax.swing.JLabel MKWarn;
    private javax.swing.JPasswordField MatKhauTxt;
    private javax.swing.JFormattedTextField NgaySinhTxt;
    private javax.swing.JLabel NgaySinhWarn;
    private javax.swing.JButton OkBtn;
    private javax.swing.JTextField PhuongTxt;
    private javax.swing.JLabel PhuongWarn;
    private javax.swing.JTextField QuanTxt;
    private javax.swing.JLabel QuanWarn;
    private javax.swing.JTextField SDTTxt;
    private javax.swing.JLabel SDTWarn;
    private javax.swing.JTextField SoNhaTxt;
    private javax.swing.JLabel SoNhaWarn;
    private javax.swing.JLabel TKWarn;
    private javax.swing.JTextField TaiKhoanTxt;
    private javax.swing.JTextField TenTxt;
    private javax.swing.JLabel TenWarn;
    private javax.swing.JTextField ThanhPhoTxt;
    private javax.swing.JLabel ThanhPhoWarn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
