/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlch;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class ThongKeSanPham extends javax.swing.JFrame {
    DefaultTableModel tblModel;
    /**
     * Creates new form ThongKeSanPham
     */
    public ThongKeSanPham() {
        initComponents();
        this.setLocationRelativeTo(null);
        initTable();
        loadAllEmployees();
    }

    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã cửa hàng", "Số nhà", "Đường", "Phường", "Quận", "Thành phố", "Mã quản lý"});
        jTable_cuahang.setModel(tblModel);
    }
    
    private void loadAllEmployees(){
        try{
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlycuahang";
            String username = "sa";
            String password = "123456";
            Connection conn = DriverManager.getConnection(url, username, password);
            
            String sql = "Select * from CUAHANG";
            PreparedStatement statement ;
            
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(sql);
            tblModel.setRowCount(0);
            while(rs.next()){
                String row[] = new String[]{
                    rs.getString("MaCH"), rs.getString("SoNha_CH"), rs.getString("Duong_CH"), rs.getString("Phuong_CH"), rs.getString("Quan_CH"), rs.getString("TPho_CH"), rs.getString("MaQL")
                };
                tblModel.addRow(row);
            }
            tblModel.fireTableDataChanged();
            rs.close();
            s.close();
            conn.close();
        } catch (Exception ex){
                ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cuahang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_mach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_timkiem = new javax.swing.JButton();
        jLabel_banchay = new javax.swing.JLabel();
        jLabel_khongchay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THỐNG KÊ SẢN PHẨM ĐÃ BÁN");

        jTable_cuahang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cửa hàng", "Số nhà", "Đường ", "Phường", "Quận", "Thành phố", "Mã quản lý"
            }
        ));
        jScrollPane1.setViewportView(jTable_cuahang);

        jLabel2.setText("Mã cửa hàng");

        jLabel3.setText("Sản phẩm bán chạy: ");

        jLabel4.setText("Sản phẩm bán không chạy: ");

        jButton_timkiem.setText("Tìm kiếm");
        jButton_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_timkiemMouseClicked(evt);
            }
        });

        jLabel_banchay.setText("---");

        jLabel_khongchay.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_mach, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_timkiem)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_banchay, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_khongchay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_mach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_timkiem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel_banchay))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel_khongchay))))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_timkiemMouseClicked
        // TODO add your handling code here:
       String mach = jTextField_mach.getText();
       try{
           if(mach.trim().length() == 0){
               loadAllEmployees();
           }
           else{
                try {
            
                    String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlycuahang";
                    String username = "sa";
                    String password = "123456";
                    Connection conn = DriverManager.getConnection(url, username, password);
                    
                    String sql = "select * from CUAHANG where MaCH = '"+jTextField_mach.getText()+"'";
                       
                    PreparedStatement statement = null;
                    statement = conn.prepareStatement(sql);   
                    ResultSet rs = statement.executeQuery();
                    tblModel.setRowCount(0);
                    while(rs.next()) {
                        String row[] = new String[]{
                            rs.getString("MaCH"), rs.getString("SoNha_CH"), rs.getString("Duong_CH"), rs.getString("Phuong_CH"), rs.getString("Quan_CH"), rs.getString("TPho_CH"), rs.getString("MaQL")
                            };
                        tblModel.addRow(row);
                        }
                      } catch (Exception ex){
                    ex.printStackTrace();
                    }
                
                
                }
            }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_timkiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_banchay;
    private javax.swing.JLabel jLabel_khongchay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_cuahang;
    private javax.swing.JTextField jTextField_mach;
    // End of variables declaration//GEN-END:variables
}
