/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlch;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author PC
 */
public class ThongKeDoanhThu extends javax.swing.JFrame {
    DefaultTableModel tblModel;
    /**
     * Creates new form ThongKeDoanhThu
     */
    public ThongKeDoanhThu() {
        initComponents();
        this.setLocationRelativeTo(null);
        initTable();
        loadAllEmployees();
    }

    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã cửa hàng", "Tháng", "Năm", "Doanh số", "QuotaSale", "Thưởng"});
        tblEmployees.setModel(tblModel);
    }
    
    private void loadAllEmployees(){
        try{
            String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlycuahang";
            String username = "sa";
            String password = "123456";
            Connection conn = DriverManager.getConnection(url, username, password);
            
            String sql = "Select * from THONGKECUAHANG";
            PreparedStatement statement ;
            
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(sql);
            tblModel.setRowCount(0);
            while(rs.next()){
                String row[] = new String[]{
                    rs.getString("MaCH"), rs.getString("Thang_CH"), rs.getString("Nam_CH"), rs.getString("DoanhSo_CH"), rs.getString("QuotaSale_CH"), rs.getString("Thuong")
                };
                tblModel.addRow(row);
            }
            tblModel.fireTableDataChanged();
            rs.close();
            s.close();
            conn.close();
        } catch (Exception ex){
                ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_mach = new javax.swing.JTextField();
        jButton_timkiem = new javax.swing.JButton();
        jTextField_thang = new javax.swing.JTextField();
        jTextField_nam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THỐNG KÊ DOANH THU");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cửa hàng", "Tháng", "Năm", "Doanh số", "QuotaSale", "Thưởng"
            }
        ));
        jScrollPane1.setViewportView(tblEmployees);

        jLabel2.setText("Mã cửa hàng");

        jButton_timkiem.setText("Tìm");
        jButton_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_timkiemMouseClicked(evt);
            }
        });

        jLabel3.setText("Tháng");

        jLabel4.setText("Năm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_mach)
                    .addComponent(jTextField_thang)
                    .addComponent(jTextField_nam, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton_timkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_mach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timkiem)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_timkiemMouseClicked
        // TODO add your handling code here:
       String mach = jTextField_mach.getText();
       String thang = jTextField_thang.getText();
       String nam = jTextField_nam.getText();
       try{
           if(mach.trim().length() == 0 && thang.trim().length() == 0 && nam.trim().length() == 0){
               loadAllEmployees();
           }
           else{
                try {
            
                    String url = "jdbc:sqlserver://localhost:1433;databaseName=Quanlycuahang";
                    String username = "sa";
                    String password = "123456";
                    Connection conn = DriverManager.getConnection(url, username, password);
                    
                    String sql = null;
                    if(mach.trim().length() != 0 && thang.trim().length() != 0 && nam.trim().length() != 0){
                        sql = "select * from THONGKECUAHANG where MaCH = '"+jTextField_mach.getText()+"' and Thang_CH = "+jTextField_thang.getText()+" and Nam_CH = "+jTextField_nam.getText()+"";
                    }else{
                        if(mach.trim().length() != 0 && thang.trim().length() == 0 && nam.trim().length() == 0){
                            sql = "select * from THONGKECUAHANG where MaCH = '"+jTextField_mach.getText()+"'";
                        }else{
                            if(mach.trim().length() == 0 && thang.trim().length() != 0 && nam.trim().length() == 0){
                                sql = "select * from THONGKECUAHANG where Thang_CH = "+jTextField_thang.getText()+"";
                            }else{
                                if(mach.trim().length() == 0 && thang.trim().length() == 0 && nam.trim().length() != 0){
                                    sql = "select * from THONGKECUAHANG where Nam_CH = "+jTextField_nam.getText()+"";
                                }else{
                                    if(mach.trim().length() != 0 && thang.trim().length() != 0 && nam.trim().length() == 0){
                                        sql = "select * from THONGKECUAHANG where MaCH = '"+jTextField_mach.getText()+"' and Thang_CH = "+jTextField_thang.getText()+"";
                                    }else{
                                        if(mach.trim().length() != 0 && thang.trim().length() == 0 && nam.trim().length() != 0){
                                            sql = "select * from THONGKECUAHANG where MaCH = '"+jTextField_mach.getText()+"' and Nam_CH = "+jTextField_nam.getText()+"";
                                        }else{
                                            if(mach.trim().length() == 0 && thang.trim().length() != 0 && nam.trim().length() != 0){
                                                sql = "select * from THONGKECUAHANG where Thang_CH = "+jTextField_thang.getText()+" and Nam_CH = "+jTextField_nam.getText()+"";
                                            }
                                        }
                                    }
                                }
                            }
                        }    
                    }       
                    PreparedStatement statement = null;
                    statement = conn.prepareStatement(sql);   
                    ResultSet rs = statement.executeQuery();
                    tblModel.setRowCount(0);
                    while(rs.next()) {
                        String row[] = new String[]{
                            rs.getString("MaCH"), rs.getString("Thang_CH"), rs.getString("Nam_CH"), rs.getString("DoanhSo_CH"), rs.getString("QuotaSale_CH"), rs.getString("Thuong")
                            };
                        tblModel.addRow(row);
                        }
                      } catch (Exception ex){
                    ex.printStackTrace();
                    }
                }
            }catch (Exception ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_timkiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeDoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_mach;
    private javax.swing.JTextField jTextField_nam;
    private javax.swing.JTextField jTextField_thang;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables
}
